package com.example.android.unscramble.ui.game


const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

val allWordsList: List<String> =
    listOf("alfabet",
        "anak anjing",
        "anak-anak",
        "anekdot",
        "angin puyuh",
        "baik",
        "balon",
        "bangku",
        "bantal",
        "bebas",
        "belajar",
        "bepergian",
        "bergabung",
        "berguna",
        "berinvestaso",
        "berkeliaran",
        "berkemah",
        "berlari",
        "berlawanan",
        "berputar",
        "bersama",
        "berwarna-warni",
        "biji",
        "bingkai",
        "biola",
        "buatan sendiri",
        "buka",
        "buku",
        "bulan",
        "bunga lili",
        "bunga",
        "bungkus",
        "corong",
        "dapur",
        "di bawah",
        "dinosaurus",
        "dunia",
        "enak",
        "es",
        "gagang pintu",
        "gajah",
        "gambang",
        "gaya",
        "gigi",
        "gitar",
        "gunung",
        "gurita",
        "hebat",
        "hewan",
        "hidung",
        "hijau",
        "ikon",
        "jalan",
        "jurnal",
        "kaca",
        "kaledoskop",
        "kamera",
        "kamu",
        "kanguru",
        "kapal",
        "keahlian",
        "kebutuhan sehari-hari",
        "kecil",
        "kelas",
        "kembang kol",
        "kemeja",
        "keranjang",
        "keyboard",
        "klasik",
        "koala",
        "kopi",
        "kreatif",
        "kucing",
        "kue kering",
        "kutub",
        "labirin",
        "laut",
        "lelucon",
        "lemon",
        "lilin",
        "listrik",
        "luar biasa",
        "lukisan",
        "madu",
        "majalah",
        "makan malam",
        "makan",
        "malam",
        "marshmallow",
        "matahari terbit",
        "melepaskan",
        "melodi",
        "melompat",
        "memesan",
        "memperkenalkan",
        "memutar ulang",
        "menari",
        "mengamati bintang",
        "mengangkat",
        "mengikuti",
        "mengobrol",
        "mengundang",
        "menit",
        "merenungkan",
        "mimpi",
        "monumen",
        "musik",
        "musim dingin",
        "nama",
        "negosiasi",
        "nomor",
        "orang",
        "otomatis",
        "pelayaran",
        "pemandangan",
        "pengatur waktu",
        "pengunjung",
        "periang",
        "pesawat ruang angkasa",
        "piknik",
        "pizza",
        "podcast",
        "pohon ek",
        "potong rambut",
        "presentasi",
        "rahasia",
        "rapi",
        "resep",
        "restoran",
        "rontgen",
        "ruang kelas",
        "ruang",
        "rubah",
        "rumah es",
        "seharusnya",
        "sehat",
        "selesai",
        "semangat",
        "semua",
        "senja",
        "sepeda motor",
        "seragam",
        "seram",
        "seratus",
        "sering",
        "setengah",
        "siang hari",
        "surat",
        "tahun",
        "taksi",
        "tas kantor",
        "teburu-buru",
        "teka-teki",
        "terbaik",
        "terjadi",
        "terkikik",
        "terlambat",
        "tertawa",
        "tidak pernah",
        "timbul",
        "truk",
        "turis",
        "ulang tahun",
        "unicorn",
        "unik",
        "utara",
        "vas",
        "visi",
        "volume",
        "walrus",
        "yoga",
        "yogurt",
        "yoyo",
        "zamrud",
        "zebra",
        "zigzag",
        "zona",
        "zoologi",)